from instructions.rig import BranchEqual
from instructions.crg import LoadWord
from instructions.grd import StoreWord
from instructions.sma import Sma
from instructions.smai import Smai
from instructions.rta import Rta
from instructions.rtai import Rtai
from instructions.y import Y
from instructions.o import O
from instructions.mov import Mov
from instructions.mul import Mul
from instructions.muli import Muli
from instructions.mix import Mix
from instructions.mula import Mula
from instructions.rol import Rol

from instr_decoder import Inst_Decoder

from processor_fh import ProcesadorFullHazard


import sys
from pathlib import Path

def load_code_from_file(file_path, processor):
        p = Path(file_path).expanduser()
        if not p.is_file():
            print(f"Error: The file {file_path} does not exist.")
            return False

        lines = []
        with p.open('r', encoding='utf-8') as f:
            for i, raw in enumerate(f, 1):
                s = raw.strip()
                if not s:
                    continue
                if len(s) != 32 or any(c not in '01' for c in s):
                    print(f"Error: Invalid instruction format on line {i}: '{raw.strip()}'")
                    return False
                lines.append(s)
        if not lines:
            print("Error: No valid instructions found in the file.")
            return False
        decoder = Inst_Decoder()
        decoder.load_code(lines, processor)
        procesador.iniciarEjecucion()
        return True

if __name__ == "__main__":
    # Leer intervalo desde argumentos de la línea de comandos (si no, usar 1 por defecto)
    interval = 1.0
    path_str = None

    if len(sys.argv) >= 2:
        try:
            interval = float(sys.argv[1])
            if len(sys.argv) >= 3:
                path_str = sys.argv[2]
        except ValueError:
            path_str = sys.argv[1]
    #
    procesador = ProcesadorFullHazard(interval=interval)
    # Cargar registros y memoria de datos para pruebas
    procesador.RF.registros[0] = 7
    procesador.RF.registros[1] = 0x9e3779b97aaa7c19
    procesador.RF.registros[2] = 7
    procesador.RF.registros[9] = 5
    procesador.RF.registros[10] = 10
    procesador.DM.datos[9] = 20

    """
    Así se cargan las instrucciones con el decoder, hay que cambiar para que assembled code se cargue desde el txt 
    al decoder
    El decoder ya carga a memoria las instrucciones decodificadas
    
    assembled_code = [
    "00000000000000000000000000000000", # NOP
    "00000000000000001100100000010001", # SMA L1 L2 L3
    "00000000001111111101010000100100", # SMAI L4 L5 255
    "00000000000000100001110000110110", # RTA L6 L7 L8
    "00000000000000101110100001011001", # MUL L9 L10 L11
    "00000000000110010011010001101100", # MULI L12 L13 100
    "00000000000000000011110001111110", # Y L14 L15 L0
    "00000000000000001100100010000001", # O L1 L2 L3
    "00000000000000011001010010010100", # OEX L4 L5 L6
    "00000000000011001010000010100111", # ROTD L7 L8 50
    "00000000000001100110100010111001", # ROTI L9 L10 25
    "00000000000000110111000011001011", # NO L11 L12 L13
    "00000000000000000011110011011110"]  # MOV L14 L15 L0

    decoder = Inst_Decoder()
    decoder.load_code(assembled_code, procesador)"""
    
    if not path_str:
        path_str = input("Enter the path to the instruction file (.txt) generated by the assembler: ").strip()

    ok = load_code_from_file(path_str, procesador)
    if not ok:
        sys.exit(1)