from instr_decoder import Inst_Decoder

from processor_fh import ProcesadorFullHazard


import sys
from pathlib import Path

def load_code_from_file(file_path, processor):
        p = Path(file_path).expanduser()
        if not p.is_file():
            print(f"Error: The file {file_path} does not exist.")
            return False

        lines = []
        with p.open('r', encoding='utf-8') as f:
            for i, raw in enumerate(f, 1):
                s = raw.strip()
                if not s:
                    continue
                if len(s) != 32 or any(c not in '01' for c in s):
                    print(f"Error: Invalid instruction format on line {i}: '{raw.strip()}'")
                    return False
                lines.append(s)
        if not lines:
            print("Error: No valid instructions found in the file.")
            return False
        decoder = Inst_Decoder()
        decoder.load_code(lines, processor)
        procesador.iniciarEjecucion()
        return True

if __name__ == "__main__":
    # Leer intervalo desde argumentos de la línea de comandos (si no, usar 1 por defecto)
    interval = 1.0
    path_str = None

    if len(sys.argv) >= 2:
        try:
            print(sys.argv)
            interval = float(sys.argv[1])
            if len(sys.argv) >= 3:
                path_str = sys.argv[2]
        except ValueError:
            path_str = sys.argv[1]
    #
    step_by_step = "-S" in sys.argv or "--step" in sys.argv
    print_registers = "-R" in sys.argv or "--registers" in sys.argv
    procesador = ProcesadorFullHazard(interval=interval, print_registers=print_registers, step_by_step=step_by_step)
    if not path_str:
        path_str = input("Enter the path to the instruction file (.txt) generated by the assembler: ").strip()

    ok = load_code_from_file(path_str, procesador)
    if not ok:
        sys.exit(1)